stages:
  - run

pray:pc205:
  stage: run
  tags:
    - benchmark
    - cuda
    - pc205
  only:
    - master
  script:
    - if [[ -f ~/pdmkp_env ]]; then . ~/pdmkp_env; fi
    - mkdir -p out
    - cd out
    - cmake -G"Unix Makefiles" -DCUDA_CCBIN=/opt/rh/devtoolset-4/root/usr/bin/g++ -DCMAKE_BUILD_TYPE=Release ..
    - make all
    - cd ..
    - ~/pdmkp_testing/utils/run_tests.sh out/pray
    - ~/pdmkp_testing/utils/run_benchmarks.sh out/pray

pray:pc189:
  stage: run
  tags:
    - benchmark
    - cuda
    - pc189
  only:
    - master
  script:
    - if [[ -f ~/pdmkp_env ]]; then . ~/pdmkp_env; fi
    - mkdir -p out
    - cd out
    - cmake -G"Unix Makefiles" -DCUDA_CCBIN=/opt/rh/devtoolset-4/root/usr/bin/g++ -DCMAKE_BUILD_TYPE=Release ..
    - make all
    - cd ..
    - ~/pdmkp_testing/utils/run_tests.sh out/pray
    - ~/pdmkp_testing/utils/run_benchmarks.sh out/pray
