stages:
  - test

pray:build:
  stage: build
  tags:
    - benchmark
  only:
    - master
  script:
    - if [[ -f ~/pdmkp_testing/env ]]; then . ~/pdmkp_testing/env; fi
    - make
    - ~/pdmkp_testing/utils/run_tests.sh out/pray
    - ~/pdmkp_testing/utils/run_benchmarks.sh out/pray
