stages:
  - test

pray:test:
  stage: test
  tags:
    - benchmark
  only:
    - master
  script:
    - if [[ -f ~/pdmkp_env ]]; then . ~/pdmkp_env; fi
    - make
    - ~/pdmkp_testing/utils/run_tests.sh out/pray
    - ~/pdmkp_testing/utils/run_benchmarks.sh out/pray
