if (CMAKE_SYSTEM_NAME MATCHES "Linux")
  exec_program(cat ARGS "/proc/cpuinfo" OUTPUT_VARIABLE CPUINFO)

  string(REGEX REPLACE "^.*(sse4a).*$" "\\1" SSE_THERE ${CPUINFO})
  string(COMPARE EQUAL "sse4a" "${SSE_THERE}" SSE4A_TRUE)
  if (SSE4A_TRUE)
    set(SSE4_A_FOUND true CACHE BOOL "SSE4A available on host")
  else (SSE4A_TRUE)
    set(SSE4_A_FOUND false CACHE BOOL "SSE4A available on host")
  endif()

  string(REGEX REPLACE "^.*(avx).*$" "\\1" SSE_THERE ${CPUINFO})
  string(COMPARE EQUAL "avx" "${SSE_THERE}" AVX_TRUE)
  if (AVX_TRUE)
    set(AVX_FOUND true CACHE BOOL "AVX available")
  else()
    set(AVX_FOUND false CACHE BOOL "AVX available")
  endif()

  if (SSE4_A_FOUND OR AVX_FOUND)
    set(SIMD_FOUND true CACHE BOOL "SSE available")
  else()
    set(SIMD_FOUND false CACHE BOOL "SSE available")
  endif()
endif()
